source "https://supermarket.getchef.com"

cookbook 'selinux'
cookbook 'python'
cookbook 'mysql'
cookbook 'iptables'
cookbook 'database'
cookbook 'nginx'
cookbook 'sample-app', git: 'https://github.com/josug-book1-materials/cookbook-sample-app.git'

