source "https://supermarket.getchef.com"

cookbook 'selinux'
cookbook 'python'
cookbook 'mysql', '< 6.0.0'
cookbook 'iptables', '= 1.1.0'
cookbook 'database', '< 3.0.0'
cookbook 'mysql-chef_gem', '= 0.0.5'
cookbook 'nginx'
cookbook 'sample-app', git: 'https://github.com/josug-book1-materials/cookbook-sample-app.git'

